version: '3.8'

services:
  # ADK web app for development purposes only
  # - This service builds the ADK web application and serves it on port 8080
  adk-web:
    container_name: adk-web
    build:
      context: .
      dockerfile: adk-web/ops/Dockerfile.dev
    environment:
      PORT: 8080
      AGENTS_DIR: /app/agents
    working_dir: /app
    volumes:
      - ./agents/:/app/agents
    ports:
      - "127.0.0.1:8080:8080"

  adk-apiserver:
    container_name: adk-apiserver
    build:
      context: .
      dockerfile: adk-apiserver/ops/Dockerfile.dev
    environment:
      PORT: 8081
      AGENTS_DIR: /app/agents
    working_dir: /app
    volumes:
      - ./agents/:/app/agents
    ports:
      - "127.0.0.1:8081:8081"

  # Agent API Docs server (using swagger)
  # This makes it easy to test the Agent API endpoints, whether local or remote
  agent-api-docs:
    build:
      context: .
      dockerfile: agent-api-docs/ops/Dockerfile.dev
    volumes:
      - ./agent-api-docs/assets/:/assets/
      - ./agent-api-docs/docs/:/docs/
    ports:
      - '127.0.0.1:8082:8080'


  # AGENTS - let's have some fun with agents!
  agent-a2a-agent-master:
    container_name: agent-a2a-agent-master
    build:
      context: .
      dockerfile: agents/a2a-agent-master/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8083
      WELL_KNOWN_HOST: agent-a2a-agent-master
    volumes:
      - ./agents/a2a-agent-master/:/app
    ports:
      - "127.0.0.1:8083:8083"

  agent-hello-world-greeter:
    container_name: agent-hello-world-greeter
    build:
      context: .
      dockerfile: agents/hello-world-greeter/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8084
      WELL_KNOWN_HOST: agent-hello-world-greeter
    volumes:
      - ./agents/hello-world-greeter/:/app
    ports:
      - "127.0.0.1:8084:8084"

  agent-google-search:
    container_name: agent-google-search
    build:
      context: .
      dockerfile: agents/google-search/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8085
      WELL_KNOWN_HOST: agent-google-search
    volumes:
      - ./agents/google-search/:/app
    ports:
      - "127.0.0.1:8085:8085"

  # MCP Servers - to integrate with ADK agents too!
  mcp-server-exchange-rate:
    container_name: mcp-server-exchange-rate
    build:
      context: .
      dockerfile: mcp-servers/exchange-rate/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 9090
    volumes:
      - ./mcp-servers/exchange-rate/:/app
    ports:
      - "127.0.0.1:9090:9090"
