version: '3.8'

services:
  # ADK web app for development purposes only
  # - This service builds the ADK web application and serves it on port 8080
  adk-web:
    container_name: adk-web
    build:
      context: .
      dockerfile: adk-web/ops/Dockerfile.dev
    environment:
      PORT: 8080
      AGENTS_DIR: /app/agents
    working_dir: /app
    volumes:
      - ./agents/:/app/agents
    ports:
      - "127.0.0.1:8080:8080"

  adk-apiserver:
    container_name: adk-apiserver
    build:
      context: .
      dockerfile: adk-apiserver/ops/Dockerfile.dev
    environment:
      PORT: 8081
      AGENTS_DIR: /app/agents
    working_dir: /app
    volumes:
      - ./agents/:/app/agents
    ports:
      - "127.0.0.1:8081:8081"

  # # AGENTS - let's have some fun with agents!
  # hello-world-agent:
  #   container_name: hello-world-agent
  #   build:
  #     context: .
  #     dockerfile: hello-world-agent/ops/Dockerfile.dev
  #   working_dir: /app
  #   volumes:
  #     - ./hello-world-agent/:/app
  #   ports:
  #     - "8082:8080"

  agent-google-search:
    container_name: agent-google-search
    build:
      context: .
      dockerfile: agents/google-search/ops/Dockerfile.dev
    working_dir: /app
    volumes:
      - ./agents/google-search/:/app
    ports:
      - "8083:8083"
